---

- name: Destroy OnMetal Lab Host
  hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - name: "Remove DFW Keypair"
      local_action:
        module: rax_keypair
        credentials: './.raxpub'
        name: osic-qa-key
        region: DFW
        state: absent
      register: osic-qa-key-dfw
      tags:
        - dfw

    - name: "Remove IAD Keypair"
      local_action:
        module: rax_keypair
        credentials: './.raxpub'
        name: osic-qa-key
        region: IAD
        state: absent
      register: osic-qa-key-iad
      tags:
        - iad

    - name: "Server Destroy Request - DFW"
      local_action:
        module: rax
        credentials: './.raxpub'
        name: osic-qa-build-dfw
        flavor: onmetal-io2
        image: 9dc2bf0a-7771-45cd-a7f9-ce86ce94c548
        key_name: osic-qa-key
        wait: yes
        state: present
        region: IAD
        exact_count: yes
        count: 0
        group: osic-qa-dfw
      register: osic-qa-build-dfw
      tags:
        - dfw

    - name: "Server Destroy Request - IAD"
      local_action:
        module: rax
        credentials: './.raxpub'
        name: osic-qa-build-iad
        flavor: onmetal-io2
        image: 9dc2bf0a-7771-45cd-a7f9-ce86ce94c548
        key_name: osic-qa-key
        wait: yes
        state: present
        region: IAD
        exact_count: yes
        count: 0
        group: osic-qa-iad
      register: osic-qa-build-iad
      tags:
        - iad

    - name: "Remove current hosts file"
      local_action:
        module: file
        path: ./hosts
        state: absent
      tags:
        - always
