---

- name: "Upgrade OpenStack Ansible"
  hosts: all
  remote_user: root
  serial: 1
  
  tasks:
    - name: Checkout to a specific release
      git: 
        repo: http://github.com/openstack/openstack-ansible
        dest: /opt/openstack-ansible
        clone: no
        accept_hostkey: yes
        recursive: yes
        version: "{{ openstack_release }}"
      tags:
        - chekout-release
       
    - name: Run Upgrade.sh
      shell: export TERM=xterm; echo 'YES' | I_REALLY_KNOW_WHAT_I_AM_DOING=true scripts/run-upgrade.sh
      args:
        chdir: /opt/openstack-ansible
      retries: 3
      tags:
        - run-upgrade
