#!/usr/bin/env groovy

def osa, common
String workspace_dir 
String onmetal_ip


// *******************************
stage 'Pre-Deployment'
// *******************************

echo 'Provisioning an onMetal server and preparing it to run OSA'
node('master') {
    
    // Copy the Rax key from the Jenkins master
    dir('/home/ubuntu') {
        stash includes: '.raxpub', name: 'raxpub'
    }

    // Load the external functions using master since the git command
    // might not be available at the agent yet
    fileLoader.withGit('https://github.com/osic/qa-jenkins-onmetal.git', 'master', null, '') {
        common = fileLoader.load('jenkins/common.groovy');
        osa = fileLoader.load('jenkins/osa_onmetal.functions.groovy');
    }
    
}

node('onmetal-provisioner') {

    // Wait for the agent to finish running cloud-init
    common.wait_for_agent_setup()

    // Get the workspace directory in the agent
    workspace_dir = pwd()
    echo "The workspace directory is ${workspace_dir}"

    // Download the project repository and paste the Rax key
    git 'https://github.com/osic/qa-jenkins-onmetal.git'
    unstash 'raxpub'
    
    // Provision the onMetal host
    onmetal_ip = osa.onmetal_provision(workspace_dir)

    // Provision the VMs in the onMetal host
    osa.vm_provision()

    // Prepare the VMs to run OpenStack
    osa.vm_preparation_for_osa()

}


// *******************************
stage 'Deployment'
// *******************************

echo 'Deploying OpenStack using OSA'
node('onmetal-provisioner') {

    // Deploy OpenStack with OSA
    osa.deploy_openstack()
    
    // Install and configure Tempest on the onMetal host
    osa.configure_tempest(onmetal_ip)
    
}


// *******************************
stage 'Post-Deployment Validation'
// *******************************

echo 'Validating the OpenStack deployment'
node('onmetal-provisioner') {

    // Run the tempest tests
    osa.run_tempest_smoke_tests(onmetal_ip)

}


// *******************************
stage 'Upgrade'
// *******************************
echo 'To be defined...'


// *******************************
stage 'Post-Upgrade Validation'
// *******************************
echo 'To be defined...'


// *******************************
stage 'Reporting'
// *******************************
echo 'To be defined'


// *******************************
stage 'Clean Up'
// *******************************

echo 'Deleting the onMetal host and its VMs'
node('onmetal-provisioner') {

    // Delete VMs
    osa.delete_virtual_resources()
    
    // Delete the onMetal host
    osa.delete_onmetal(onmetal_ip)

}

